default: &default
      adapter: postgresql
      encoding: utf8
      pool: 5
      username: usuariodb
      password: contrasenadb

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production