default: &default
     adapter: postgresql
     encoding: utf8
     pool: 5
     username: neyder
     password: durfay11

development:
 <<: *default
 database: app_development

test:
 <<: *default
 database: app_test

production:
 <<: *default
 database: app_production